#!/bin/bash
SERVICE_PORT=3000
DOCKER_HOST=quay.io
DOCKER_ACCOUNT=feliun

docker run -d -p $SERVICE_PORT:$SERVICE_PORT -e SERVICE_ENV=live -e MONGO_URL=$MONGO_URL -e RABBIT_PWD=$RABBIT_PWD --name $SERVICE $DOCKER_HOST/$DOCKER_ACCOUNT/$SERVICE:latest
