ensure-dependencies:
	@npm install
	@node prepare-ec2-instance

brand:
	@echo "Nothing to brand here..."

package:
	@echo "Nothing to package here..."

qa:
	@echo "Nothing to QA here..."

archive: 
	@echo "Nothing to archive here..."

check:
	@echo "Nothing to check here..."